# Generated by Django 4.2.3 on 2023-08-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisement', '0002_advertisement_image_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создание дата'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновление дата'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='descriptions',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisments/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='trades',
            field=models.BooleanField(help_text='Если хотим торговаться', verbose_name='Торг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisment',
        ),
    ]
